### ISSUE TITLE
Log in functionality

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/business-launchpad#18]
## As as user, I want to be able to create and profile and login

- [ ] Log in page
- [ ] Sign up page
- [ ] Possibility to reset password (stretch?)

**Comment by SalwaMugh** [comment]
I would Like a **reset password** to be there , if we are comfortable at the last days of the two week build , we can do it!

**Comment by Oliversw** [comment]
Agreed @SalwaMugh !!

**Comment by teenie-quaggard** [comment]
@SalwaMugh yes, sounds good!
