### ISSUE TITLE
Complete Figma Design

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/business-launchpad#7]
- [x] landing page #8 
- [x] registration page/form #9
- [x] initial assessment form #10
- [x] dashboard #11
- [x] goals #12
- [ ] list of global styles for #3 
   - colors
   - fonts
